apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-pvc
  namespace: hands-on
spec:
  storageClassName: "local-path"
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
