apiVersion: v1
kind: Service
metadata:
  name: todo-svc
  namespace: hands-on
spec:
  type: NodePort
  selector:
    app: todo-api-backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
