apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-app
  labels:
    app: todo-api-backend
  namespace: hands-on
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-api-backend
      type: Flask-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: todo-api-backend
        type: Flask-app
    spec:
      containers:
        - name: todo-api-backend
          image: mustafa0kanaan/todo-api:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10