apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: "{{ .Release.Name }}-mongodb-0.mongodb-headless,{{ .Release.Name }}-mongodb-1.mongodb-headless,{{ .Release.Name }}-mongodb-2.mongodb-headless"
  DB_NAME: {{ .Values.db.name }}